name: d_app
description: "A new Flutter project."

# Prevent the package from being published to pub.dev
publish_to: "none"

# Define the version and build number for your app
version: 1.0.0+1

# Specify the Dart SDK version
environment:
  sdk: ">=3.5.3 <4.0.0"

# Project dependencies
dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  device_info_plus: ^11.2.1
  cupertino_icons: ^1.0.8
  intl: ^0.17.0


# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Specify assets if needed
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Specify custom fonts if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
